name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
      - name: Print stuff
        run: |
          echo "The secret is: ${{ secrets.DEMO_SECRET }} and the variable is: ${{ vars.MY_VARIABLE }}"
